import 'package:hive/hive.dart';

part 'transaction.g.dart'; // This file will be generated by `hive_generator`

@HiveType(typeId: 0) // Unique ID for your HiveType
class Transaction extends HiveObject {
  @HiveField(0)
  final String type;

  @HiveField(1)
  final String category;

  @HiveField(2)
  final String product;

  @HiveField(3)
  final String brand;

  @HiveField(4)
  final int quantity;

  @HiveField(5)
  final double unitPrice;

  @HiveField(6)
  final double total;

  @HiveField(7)
  final DateTime timestamp;

  Transaction({
    required this.type,
    required this.category,
    required this.product,
    required this.brand,
    required this.quantity,
    required this.unitPrice,
    required this.total,
    required this.timestamp,
  });
}